# Generated by Django 3.2.12 on 2022-05-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='add_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
